SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

ALTER DATABASE happylucky CHARACTER SET = utf8;
ALTER DATABASE happylucky DEFAULT CHARACTER SET = utf8;
ALTER DATABASE happylucky COLLATE = utf8_general_ci;
ALTER DATABASE happylucky DEFAULT COLLATE = utf8_general_ci;

ALTER TABLE `amulet` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `amulet_product` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `amulet_type` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `amulet_type_image` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `country` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=243;
ALTER TABLE `customer_order` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `monk` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=12;
ALTER TABLE `monk_image` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `order_detail` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `product` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `product_image` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `supplier` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `supplier_order` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `supplier_order_detail` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `customer` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `user` ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2;

INSERT INTO `country` (`id`, `country_name`, `iso_code_2`, `iso_code_3`, `postcode_required`) VALUES
(1, 'Afghanistan', 'AF', 'AFG', 1),
(2, 'Albania', 'AL', 'ALB', 0),
(3, 'Algeria', 'DZ', 'DZA', 1),
(4, 'American Samoa', 'AS', 'ASM', 0),
(5, 'Andorra', 'AD', 'AND', 0),
(6, 'Angola', 'AO', 'AGO', 0),
(7, 'Anguilla', 'AI', 'AIA', 0),
(8, 'Antarctica', 'AQ', 'ATA', 1),
(9, 'Antigua and Barbuda', 'AG', 'ATG', 0),
(10, 'Argentina', 'AR', 'ARG', 1),
(11, 'Armenia', 'AM', 'ARM', 1),
(12, 'Aruba', 'AW', 'ABW', 0),
(13, 'Australia', 'AU', 'AUS', 1),
(14, 'Austria', 'AT', 'AUT', 1),
(15, 'Azerbaijan', 'AZ', 'AZE', 1),
(16, 'Bahamas', 'BS', 'BHS', 0),
(17, 'Bahrain', 'BH', 'BHR', 0),
(18, 'Bangladesh', 'BD', 'BGD', 1),
(19, 'Barbados', 'BB', 'BRB', 0),
(20, 'Belarus', 'BY', 'BLR', 1),
(21, 'Belgium', 'BE', 'BEL', 1),
(22, 'Belize', 'BZ', 'BLZ', 0),
(23, 'Benin', 'BJ', 'BEN', 0),
(24, 'Bermuda', 'BM', 'BMU', 0),
(25, 'Bhutan', 'BT', 'BTN', 0),
(26, 'Bolivia', 'BO', 'BOL', 0),
(27, 'Bosnia and Herzegowina', 'BA', 'BIH', 1),
(28, 'Botswana', 'BW', 'BWA', 0),
(29, 'Bouvet Island', 'BV', 'BVT', 1),
(30, 'Brazil', 'BR', 'BRA', 1),
(31, 'British Indian Ocean Territory', 'IO', 'IOT', 1),
(32, 'Brunei Darussalam', 'BN', 'BRN', 0),
(33, 'Bulgaria', 'BG', 'BGR', 1),
(34, 'Burkina Faso', 'BF', 'BFA', 0),
(35, 'Burundi', 'BI', 'BDI', 0),
(36, 'Cambodia', 'KH', 'KHM', 0),
(37, 'Cameroon', 'CM', 'CMR', 0),
(38, 'Canada', 'CA', 'CAN', 1),
(39, 'Cape Verde', 'CV', 'CPV', 0),
(40, 'Cayman Islands', 'KY', 'CYM', 0),
(41, 'Central African Republic', 'CF', 'CAF', 0),
(42, 'Chad', 'TD', 'TCD', 0),
(43, 'Chile', 'CL', 'CHL', 0),
(44, 'China', 'CN', 'CHN', 1),
(45, 'Christmas Island', 'CX', 'CXR', 1),
(46, 'Cocos (Keeling) Islands', 'CC', 'CCK', 1),
(47, 'Colombia', 'CO', 'COL', 0),
(48, 'Comoros', 'KM', 'COM', 1),
(49, 'Congo', 'CG', 'COG', 0),
(50, 'Cook Islands', 'CK', 'COK', 0),
(51, 'Costa Rica', 'CR', 'CRI', 0),
(52, 'Cote D''Ivoire', 'CI', 'CIV', 1),
(53, 'Croatia', 'HR', 'HRV', 1),
(54, 'Cuba', 'CU', 'CUB', 1),
(55, 'Cyprus', 'CY', 'CYP', 1),
(56, 'Czech Republic', 'CZ', 'CZE', 1),
(57, 'Denmark', 'DK', 'DNK', 1),
(58, 'Djibouti', 'DJ', 'DJI', 0),
(59, 'Dominica', 'DM', 'DMA', 0),
(60, 'Dominican Republic', 'DO', 'DOM', 0),
(61, 'East Timor', 'TP', 'TMP', 1),
(62, 'Ecuador', 'EC', 'ECU', 0),
(63, 'Egypt', 'EG', 'EGY', 0),
(64, 'El Salvador', 'SV', 'SLV', 0),
(65, 'Equatorial Guinea', 'GQ', 'GNQ', 0),
(66, 'Eritrea', 'ER', 'ERI', 0),
(67, 'Estonia', 'EE', 'EST', 1),
(68, 'Ethiopia', 'ET', 'ETH', 0),
(69, 'Falkland Islands (Malvinas)', 'FK', 'FLK', 1),
(70, 'Faroe Islands', 'FO', 'FRO', 1),
(71, 'Fiji', 'FJ', 'FJI', 0),
(72, 'Finland', 'FI', 'FIN', 1),
(73, 'France', 'FR', 'FRA', 1),
(74, 'France, Metropolitan', 'FX', 'FXX', 1),
(75, 'French Guiana', 'GF', 'GUF', 0),
(76, 'French Polynesia', 'PF', 'PYF', 0),
(77, 'French Southern Territories', 'TF', 'ATF', 1),
(78, 'Gabon', 'GA', 'GAB', 0),
(79, 'Gambia', 'GM', 'GMB', 0),
(80, 'Georgia', 'GE', 'GEO', 1),
(81, 'Germany', 'DE', 'DEU', 1),
(82, 'Ghana', 'GH', 'GHA', 0),
(83, 'Gibraltar', 'GI', 'GIB', 0),
(84, 'Greece', 'GR', 'GRC', 1),
(85, 'Greenland', 'GL', 'GRL', 1),
(86, 'Grenada', 'GD', 'GRD', 0),
(87, 'Guadeloupe', 'GP', 'GLP', 0),
(88, 'Guam', 'GU', 'GUM', 0),
(89, 'Guatemala', 'GT', 'GTM', 0),
(90, 'Guinea', 'GN', 'GIN', 0),
(91, 'Guinea-bissau', 'GW', 'GNB', 0),
(92, 'Guyana', 'GY', 'GUY', 0),
(93, 'Haiti', 'HT', 'HTI', 0),
(94, 'Heard and Mc Donald Islands', 'HM', 'HMD', 1),
(95, 'Honduras', 'HN', 'HND', 0),
(96, 'Hong Kong', 'HK', 'HKG', 0),
(97, 'Hungary', 'HU', 'HUN', 1),
(98, 'Iceland', 'IS', 'ISL', 1),
(99, 'India', 'IN', 'IND', 1),
(100, 'Indonesia', 'ID', 'IDN', 1),
(101, 'Iran (Islamic Republic of)', 'IR', 'IRN', 1),
(102, 'Iraq', 'IQ', 'IRQ', 0),
(103, 'Ireland', 'IE', 'IRL', 0),
(104, 'Israel', 'IL', 'ISR', 1),
(105, 'Italy', 'IT', 'ITA', 1),
(106, 'Jamaica', 'JM', 'JAM', 0),
(107, 'Japan', 'JP', 'JPN', 1),
(108, 'Jordan', 'JO', 'JOR', 0),
(109, 'Kazakhstan', 'KZ', 'KAZ', 1),
(110, 'Kenya', 'KE', 'KEN', 0),
(111, 'Kiribati', 'KI', 'KIR', 0),
(112, 'North Korea', 'KP', 'PRK', 1),
(113, 'Korea, Republic of', 'KR', 'KOR', 1),
(114, 'Kuwait', 'KW', 'KWT', 0),
(115, 'Kyrgyzstan', 'KG', 'KGZ', 1),
(116, 'Lao People''s Democratic Republic', 'LA', 'LAO', 0),
(117, 'Latvia', 'LV', 'LVA', 1),
(118, 'Lebanon', 'LB', 'LBN', 0),
(119, 'Lesotho', 'LS', 'LSO', 0),
(120, 'Liberia', 'LR', 'LBR', 0),
(121, 'Libyan Arab Jamahiriya', 'LY', 'LBY', 1),
(122, 'Liechtenstein', 'LI', 'LIE', 1),
(123, 'Lithuania', 'LT', 'LTU', 1),
(124, 'Luxembourg', 'LU', 'LUX', 1),
(125, 'Macau', 'MO', 'MAC', 0),
(126, 'Macedonia', 'MK', 'MKD', 1),
(127, 'Madagascar', 'MG', 'MDG', 0),
(128, 'Malawi', 'MW', 'MWI', 1),
(129, 'Malaysia', 'MY', 'MYS', 1),
(130, 'Maldives', 'MV', 'MDV', 0),
(131, 'Mali', 'ML', 'MLI', 0),
(132, 'Malta', 'MT', 'MLT', 0),
(133, 'Marshall Islands', 'MH', 'MHL', 1),
(134, 'Martinique', 'MQ', 'MTQ', 1),
(135, 'Mauritania', 'MR', 'MRT', 0),
(136, 'Mauritius', 'MU', 'MUS', 0),
(137, 'Mayotte', 'YT', 'MYT', 1),
(138, 'Mexico', 'MX', 'MEX', 1),
(139, 'Micronesia, Federated States of', 'FM', 'FSM', 1),
(140, 'Moldova, Republic of', 'MD', 'MDA', 1),
(141, 'Monaco', 'MC', 'MCO', 1),
(142, 'Mongolia', 'MN', 'MNG', 1),
(143, 'Montserrat', 'MS', 'MSR', 0),
(144, 'Morocco', 'MA', 'MAR', 0),
(145, 'Mozambique', 'MZ', 'MOZ', 0),
(146, 'Myanmar', 'MM', 'MMR', 1),
(147, 'Namibia', 'NA', 'NAM', 0),
(148, 'Nauru', 'NR', 'NRU', 1),
(149, 'Nepal', 'NP', 'NPL', 0),
(150, 'Netherlands', 'NL', 'NLD', 1),
(151, 'Netherlands Antilles', 'AN', 'ANT', 0),
(152, 'New Caledonia', 'NC', 'NCL', 0),
(153, 'New Zealand', 'NZ', 'NZL', 1),
(154, 'Nicaragua', 'NI', 'NIC', 0),
(155, 'Niger', 'NE', 'NER', 0),
(156, 'Nigeria', 'NG', 'NGA', 0),
(157, 'Niue', 'NU', 'NIU', 1),
(158, 'Norfolk Island', 'NF', 'NFK', 0),
(159, 'Northern Mariana Islands', 'MP', 'MNP', 0),
(160, 'Norway', 'NO', 'NOR', 1),
(161, 'Oman', 'OM', 'OMN', 0),
(162, 'Pakistan', 'PK', 'PAK', 1),
(163, 'Palau', 'PW', 'PLW', 1),
(164, 'Panama', 'PA', 'PAN', 0),
(165, 'Papua New Guinea', 'PG', 'PNG', 0),
(166, 'Paraguay', 'PY', 'PRY', 0),
(167, 'Peru', 'PE', 'PER', 0),
(168, 'Philippines', 'PH', 'PHL', 1),
(169, 'Pitcairn', 'PN', 'PCN', 1),
(170, 'Poland', 'PL', 'POL', 1),
(171, 'Portugal', 'PT', 'PRT', 1),
(172, 'Puerto Rico', 'PR', 'PRI', 1),
(173, 'Qatar', 'QA', 'QAT', 0),
(174, 'Reunion', 'RE', 'REU', 1),
(175, 'Romania', 'RO', 'ROM', 1),
(176, 'Russian Federation', 'RU', 'RUS', 1),
(177, 'Rwanda', 'RW', 'RWA', 0),
(178, 'Saint Kitts and Nevis', 'KN', 'KNA', 1),
(179, 'Saint Lucia', 'LC', 'LCA', 1),
(180, 'Saint Vincent and the Grenadines', 'VC', 'VCT', 1),
(181, 'Samoa', 'WS', 'WSM', 1),
(182, 'San Marino', 'SM', 'SMR', 1),
(183, 'Sao Tome and Principe', 'ST', 'STP', 1),
(184, 'Saudi Arabia', 'SA', 'SAU', 1),
(185, 'Senegal', 'SN', 'SEN', 0),
(186, 'Seychelles', 'SC', 'SYC', 0),
(187, 'Sierra Leone', 'SL', 'SLE', 0),
(188, 'Singapore', 'SG', 'SGP', 1),
(189, 'Slovak Republic', 'SK', 'SVK', 1),
(190, 'Slovenia', 'SI', 'SVN', 1),
(191, 'Solomon Islands', 'SB', 'SLB', 0),
(192, 'Somalia', 'SO', 'SOM', 1),
(193, 'South Africa', 'ZA', 'ZAF', 1),
(194, 'South Georgia &amp; South Sandwich Islands', 'GS', 'SGS', 1),
(195, 'Spain', 'ES', 'ESP', 1),
(196, 'Sri Lanka', 'LK', 'LKA', 1),
(197, 'St. Helena', 'SH', 'SHN', 1),
(198, 'St. Pierre and Miquelon', 'PM', 'SPM', 1),
(199, 'Sudan', 'SD', 'SDN', 1),
(200, 'Suriname', 'SR', 'SUR', 0),
(201, 'Svalbard and Jan Mayen Islands', 'SJ', 'SJM', 1),
(202, 'Swaziland', 'SZ', 'SWZ', 0),
(203, 'Sweden', 'SE', 'SWE', 1),
(204, 'Switzerland', 'CH', 'CHE', 1),
(205, 'Syrian Arab Republic', 'SY', 'SYR', 0),
(206, 'Taiwan', 'TW', 'TWN', 1),
(207, 'Tajikistan', 'TJ', 'TJK', 1),
(208, 'Tanzania, United Republic of', 'TZ', 'TZA', 0),
(209, 'Thailand', 'TH', 'THA', 1),
(210, 'Togo', 'TG', 'TGO', 0),
(211, 'Tokelau', 'TK', 'TKL', 1),
(212, 'Tonga', 'TO', 'TON', 0),
(213, 'Trinidad and Tobago', 'TT', 'TTO', 0),
(214, 'Tunisia', 'TN', 'TUN', 0),
(215, 'Turkey', 'TR', 'TUR', 1),
(216, 'Turkmenistan', 'TM', 'TKM', 1),
(217, 'Turks and Caicos Islands', 'TC', 'TCA', 0),
(218, 'Tuvalu', 'TV', 'TUV', 0),
(219, 'Uganda', 'UG', 'UGA', 0),
(220, 'Ukraine', 'UA', 'UKR', 1),
(221, 'United Arab Emirates', 'AE', 'ARE', 0),
(222, 'United Kingdom', 'GB', 'GBR', 1),
(223, 'United States', 'US', 'USA', 1),
(224, 'United States Minor Outlying Islands', 'UM', 'UMI', 1),
(225, 'Uruguay', 'UY', 'URY', 1),
(226, 'Uzbekistan', 'UZ', 'UZB', 1),
(227, 'Vanuatu', 'VU', 'VUT', 0),
(228, 'Vatican City State (Holy See)', 'VA', 'VAT', 1),
(229, 'Venezuela', 'VE', 'VEN', 0),
(230, 'Viet Nam', 'VN', 'VNM', 1),
(231, 'Virgin Islands (British)', 'VG', 'VGB', 0),
(232, 'Virgin Islands (U.S.)', 'VI', 'VIR', 1),
(233, 'Wallis and Futuna Islands', 'WF', 'WLF', 0),
(234, 'Western Sahara', 'EH', 'ESH', 1),
(235, 'Yemen', 'YE', 'YEM', 0),
(236, 'Yugoslavia', 'YU', 'YUG', 1),
(237, 'Democratic Republic of Congo', 'CD', 'COD', 1),
(238, 'Zambia', 'ZM', 'ZMB', 0),
(239, 'Zimbabwe', 'ZW', 'ZWE', 0),
(240, 'Channel Islands', 'CI', 'CHI', 0),
(241, 'Serbia (Republic of)', 'RS', 'SRB', 0),
(242, 'Montenegro (Republic of)', 'ME', 'MNE', 0);

INSERT INTO `user` (`id`, `first_name`, `last_name`, `email`, `password`, `salt`, `security_question`, `security_answer`) VALUES
(1, 'admin', 'admin', 'admin@happylucky.com', '48367792e29476308ad94e26d9fc58e7552754bd', 'c13fe37efaa711de8272f1a726bc1413', 'Which year is this project started?', '2011');

INSERT INTO `monk` (`id`, `monk_name`, `monk_story`) VALUES 
(1, 'Ah Chan Tim (阿参添)', 'Description'),
(2, 'Ah Chan Do (阿参多)', 'Description'),
(3, 'Long Phor Thuad (龙泡托)', 'Description'),
(4, 'Long Phor Tim (龙泡添)', 'Description'),
(5, 'Than Tit (陈铁)', 'Description'),
(6, 'Tok Raja (夺拉惹)', 'Description'),
(7, 'Than Chan (陈展)', 'Description'),
(8, 'Than Lek (陈烈)', 'Description'),
(9, 'Chao Kun Onn (招昆安)', 'Description'),
(10, 'Ah Chan Deng (阿参廷)', 'Description'),
(11, 'Ah Chan Kao (阿参叩)', 'Description');
